language: php

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - wget http://getcomposer.org/composer.phar
  - php -d memory_limit=-1 composer.phar install
  - phpunit